#ifndef CONNECTION_STATE_H
#define CONNECTION_STATE_H

enum ConnectionState { STATE_NEW = 0, STATE_CONNECTING1, STATE_CONNECTING2, STATE_BAD_CONNECTION_SEQUENCE, STATE_CONNECTED, STATE_CLOSING, STATE_RESET, STATE_CLOSED1, STATE_CLOSED2, STATE_CLOSED, STATE_UNKNOWN }; 

//std::ostream& operator<< (std::ostream & os, ConnectionState state);

#endif

